version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: make mongodb-test-server
      - run: ./cc-test-reporter before-build
      - run: make image
      - run: make citest
      - run:
          name: "Upload coverage"
          command: ./cc-test-reporter after-build --prefix="/app"
          environment:
              CC_TEST_REPORTER_ID: 787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
